### PR TITLE
Add support for a configurable base URL

### PR DESCRIPTION
**Pull request by misterbyrne**
I work on an app whose dev environments serve it via Rails app. This means relative URLs for the `_hot-load` middleware don't work. Using the `rootURL` doesn't work either.

I've added a config parameter here to allow us to override the base URL used when constructing a URL to the hot load middleware (in our case we also need to supply the port here to bypass the Rails app and go straight to the hot-loader middleware).

### CODE REVIEW

**Comment by lifeart** [comment]
Hi @misterbyrne! Thank you for this pr! Could you add readme section, describing this config param?

**Comment by misterbyrne** [comment]
I also reworded a few things in the README that I found confusing when originally configuring the add-on for my own app. I'm happy to roll those back if you think they're off topic.

Also, it might be possible to remove the section about the known CSP issue now.

**Comment by lifeart** [comment]
@misterbyrne thank you! And yes, if CSP issue disappeared, let's remove it from description!

**Comment by lifeart** [comment]
@misterbyrne thank you for contribution! `ember-ast-hot-load@0.0.83` published

**Pull request merged**
